# Generated by Django 4.1.3 on 2022-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_type", models.CharField(max_length=200)),
                ("rate_date", models.DateField()),
                ("rate_value", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
