#!/bin/bash

python3 Global_Rates/global_rates.py Global_Rates/configs/BACEN_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/BI_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/BOC_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/BOE_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/BOI_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/BOJ_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/cbr_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_chile_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_hungary_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_mexico_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_new_zealand_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_norway_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_poland_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_south_korea_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_sweden_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_swiss_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/central_bank_turkey_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/CNB_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/ECB_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/ester.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/euribor_12m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/euribor_1m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/euribor_1w.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/euribor_3m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/euribor_6m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/fed_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_gbp_1m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_gbp_3m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_gbp_6m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_jpy_1m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_jpy_3m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_jpy_6m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_usd_12m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_usd_1d.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_usd_1m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_usd_3m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/libor_usd_6m.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/nationalbanken_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/PBC_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/rba_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/RBI_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/sana_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/sarb_rate.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/saron.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/sofr.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/sonia.ini
python3 Global_Rates/global_rates.py Global_Rates/configs/tonar.ini
